name: run-reminder

on:
  workflow_dispatch:
  schedule:
    - cron: '00 7 * * *' #utcなので9時間マイナスで日本時間になる
    # - cron: '00 7 * * 1-5 ' 平日16時

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: run-compose
      run: docker-compose up -d --build
    
    - name: run-npm-install-on-container
      run: docker-compose exec -T reminder npm install
      
    - name: run-reminder
      run: docker-compose exec -T reminder node src/index.js

    - name: stop-containers
      if: always()
      run: docker-compose down
