name: run-reminder

on:
  workflow_dispatch:
  schedule:
   - cron: '00 7 * * 1-5' # 平日16時(github actions実行時間がUTCなので9時間マイナスで日本時間になる)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: run-compose
      env:
       HEALTHCAREINPUT_BASEURL: ${{secrets.HEALTHCAREINPUT_BASEURL}}
       SPREADSHEET_ID: ${{secrets.SPREADSHEET_ID}}
       FORMDATASHEET_ID: ${{secrets.FORMDATASHEET_ID}}
       USERMASTERSHEET_ID: ${{secrets.USERMASTERSHEET_ID}}
       WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}    
      run: docker-compose up -d --build
    
    - name: copy-google-spreadsheet-api-credentials
      env:
       SPREADSHEET_SECRETS: ${{secrets.GOOGLE_SPREADSHEET_API_SECRETS}}
      run: echo $SPREADSHEET_SECRETS | base64 --decode --ignore-garbage > ./credentials.json

    - name: run-reminder
      run: docker-compose exec -T reminder node src/index.js

    - name: delete-credentials
      run: rm -rf ./credentials.json

    - name: stop-containers
      if: always()
      run: docker-compose down
